services:
  local:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  github-action:
    image: codykilpatrick/portfolio:latest
    environment:
      NODE_ENV: production
  github-action-ghcr:
    image: ghcr.io/codykilpatrick/portfolio-react:latest
    environment:
      NODE_ENV: production