services:
  local:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  github-action:
    image: codykilpatrick/portfolio:latest
    environment:
      NODE_ENV: production
    # You can specify any other configurations needed for GitHub Actions here
