name: Baseline Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  test:
    - name: Checkout
        uses: actions/checkout@v2