name: CI to Docker hub

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  compile:
      name: Compile site assets
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Run the build process with Docker
          uses: addnab/docker-run-action@v3
          with:
              image: aschmelyun/cleaver:latest
              options: -v ${{ github.workspace }}:/var/www
              run: |
                  composer install
                  npm install
                  npm run production