name: Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add the npm install step to install project dependencies
      - name: Install Node.js Dependencies
        run: npm install

      # Add the step to build your Docker image using Docker Compose
      - name: Build Docker image
        run: docker-compose build

      # Add the step to pull your Docker image (if needed)
      - name: Pull Docker image
        run: docker pull codykilpatrick/portfolio:latest

      # Your other steps go here...

      # For example, you can start your Docker container with Docker Compose
      - name: Start Docker container
        run: docker-compose up -d