name: Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add the npm install step to install project dependencies
      - name: Install Node.js Dependencies
        run: npm install

      # Add the step to pull your Docker image
      - name: Pull Docker image
        run: docker pull codykilpatrick/portfolio:latest

      # Add a step to run tests inside a Docker container
      - name: Run Tests
        run: |
          docker run --rm -v "$(pwd)":/app -w /app codykilpatrick/portfolio:latest \
          sh -c "npm test" || (echo 'Tests failed' && exit 1)