name: Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add the step to run the Docker container
      - name: Run Docker Container
        run: |
          docker run -d --name my_container -v "$(pwd)":/app -w /app codykilpatrick/portfolio:latest sleep infinity

      # Add a step to execute tests inside the running Docker container
      - name: Run Tests
        run: |
          docker exec my_container sh -c "npm test" || (echo 'Tests failed' && exit 1)

      # Cleanup: Stop and remove the Docker container
      - name: Cleanup Docker Container
        run: |
          docker stop my_container
          docker rm my_container