name: CI to Docker hub

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker layers cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check if Docker image exists
        id: check_image
        run: |
          IMAGE=codykilpatrick/portfolio:${{ github.sha }}
          if docker manifest inspect $IMAGE &>/dev/null; then
            echo "::set-output name=image_exists::true"
          else
            echo "::set-output name=image_exists::false"
          fi

      - name: Build and push Docker image
        id: docker_build
        run: |
          if [[ "${{ steps.check_image.outputs.image_exists }}" == "false" ]]; then
            docker build -t codykilpatrick/portfolio:${{ github.sha }} .
            docker push codykilpatrick/portfolio:${{ github.sha }}
          fi

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Pull and use Docker image
        run: |
          docker pull codykilpatrick/portfolio:${{ github.sha }}
          docker run -d codykilpatrick/portfolio:${{ github.sha }} echo "Docker image test successful"
