name: Cache In GHCR

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/compose.yaml'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: codykilpatrick  # Use your lowercase username here
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx create --use
          docker buildx build --push --tag ghcr.io/codykilpatrick/portfolio-react:latest .
        env:
          DOCKER_CLI_AGGREGATE: 1

      - name: Clean up
        run: docker buildx prune -f
